RazorPageProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPageProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPageProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPageProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorPageProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPageProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPageProject/Pages/TodoList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Model;

namespace RazorPageProject.Pages.TodoList
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public ToDo ToDo { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _db.ToDo.AddAsync(ToDo);
                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

RazorPageProject/Pages/TodoList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPageProject.Model;

namespace RazorPageProject.Pages.TodoList
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IEnumerable<ToDo> ToDos { get; set; }
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public ToDo ToDo { get; set; }
        public async Task  OnGet()
        {
            ToDos = await _db.ToDo.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var todo = await _db.ToDo.FindAsync(id);
            if (todo == null)
            {
                return NotFound();
            }
   
             
             _db.Remove(todo);
             await _db.SaveChangesAsync();
             return RedirectToPage();


        }

        public async Task<IActionResult> OnPostComplete(int id)
        {
            var todo = await _db.ToDo.FindAsync(id);
            if (todo == null)
            {
                return NotFound();
            }
            todo.Task = todo.Task;
            todo.Status = 100;
            todo.Priority = todo.Priority;
            todo.date = todo.date;
            await _db.SaveChangesAsync();
            return RedirectToPage();
            

        }
    }
}

RazorPageProject/Pages/TodoList/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Model;

namespace RazorPageProject.Pages.TodoList
{
    public class ViewModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public ViewModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public ToDo ToDo { get; set; }
        public async Task OnGet(int id)
        {
            ToDo = await _db.ToDo.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var TodoDb = await _db.ToDo.FindAsync(ToDo.Id);
                TodoDb.Task = ToDo.Task;
                TodoDb.Status = ToDo.Status;
                TodoDb.Priority = ToDo.Priority;
                TodoDb.date = ToDo.date;
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }

        }
    }
}

RazorPageProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorPageProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPageProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="table-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPageProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TodoList/Index">Items List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RazorPageProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RazorPageProject/Pages/TodoList/Create.cshtml
@page
@model RazorPageProject.Pages.TodoList.CreateModel


<h1 class=" text-center text-info">Create New Task</h1>
<br />

<div class="border container" style="padding:30px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class=" = form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Task"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Task" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Task" class="text-danger"></span>
        </div>

        <div class=" = form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Status"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Status" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Status" class="text-danger"></span>

        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Priority"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Priority" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Priority" class="text-danger"></span>

        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ToDo.date"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.date" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.date" class="text-danger"></span>

        </div>

        <div class="form-group row ">
            <div class=" col-3  offset-3">
                <button class="btn btn-success  form-control">Create Item</button>
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-info form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

RazorPageProject/Pages/TodoList/Index.cshtml
@page
@model RazorPageProject.Pages.TodoList.IndexModel
@*<h1 class=" offset-6 text-info">My list</h1>*@
<br />

<div class="container row p-0 m-0">
    <div class="col-9">
        <h1 class=" text-uppercase text-info">To Do List</h1>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-success form-control text-white">Create new Item</a>
    </div>
</div>
<br />


<div class="col-12 border bg-white p-3 mt-3">
    <form method="post">
        @if (Model.ToDos.Count() > 0)
        {
        <table class="table  table-stripped border">
            <tr class="table-secondary col-12">
                <th>
                    <label asp-for="ToDos.FirstOrDefault().Task"></label>
                </th>
                <th>
                    <label asp-for="ToDos.FirstOrDefault().Status"></label>
                </th>
                <th>
                    <label asp-for="ToDos.FirstOrDefault().date"></label>
                </th>
           
            </tr>
                @foreach (var item in Model.ToDos)
                {
                    @if (item.Status <= 99)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item.Task)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.date)
                        </td>
                        <td class="col-1">
                            <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are You Sure You want to Delete')" class="btn-danger btn-sm">Delete</button>
                        </td>
                        <td class="col-1">
                            <a asp-route-id="@item.Id" class="btn btn-info btn-sm" asp-page="View">View</a>
                        </td>
                        <td class="col-1">
                            <input hidden asp-for="@item.Id" />
                            <button asp-page-handler="Complete" onclick="return confirm('The task will be marked as Complete')" asp-route-id="@item.Id" class="btn btn-success btn-sm">Complete</button>
                        </td>

                    </tr>
                    }
                    else

                    {
                     <tr>
                        <td>
                             @Html.DisplayFor(m => item.Task)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Status)
                        </td>
                        <td>
                             @Html.DisplayFor(m => item.date)
                        </td>
                        <td class="col-1">
                            <button asp-page-handler="Delete" onclick="return confirm('Are You Sure You want to Delete')"
                                    class="btn-danger" asp-route-id="@item.Id">
                                Delete
                            </button>
                            
                        </td>
                         
                    </tr>


                     }

                  }
                </table>
            }
            else
            {
                <h5 class="text-danger">You have No Pending task</h5>
            }
    </form>
</div>

RazorPageProject/Pages/TodoList/View.cshtml
@page
@model RazorPageProject.Pages.TodoList.ViewModel


<h1 class=" text-center text-info">View and Update Task</h1>
<br />

<div class="border container" style="padding:30px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <input hidden asp-for="ToDo.Id" />
        <div class=" = form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Task"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Task" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Task" class="text-danger"></span>
        </div>

        <div class=" = form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Status"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Status" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Status" class="text-danger"></span>

        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ToDo.Priority"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.Priority" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.Priority" class="text-danger"></span>

        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ToDo.date"></label>
            </div>
            <div class="col-6">
                <input asp-for="ToDo.date" class="form-control" />
            </div>
            <span asp-validation-for="ToDo.date" class="text-danger"></span>

        </div>

        <div class="form-group row ">
            <div class=" col-3  offset-3">
                <button class="btn btn-success form-control">Update Item</button>
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-info form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}